# Generated by Django 4.0.6 on 2022-08-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_name_student_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subject',
            new_name='Subject',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='Teacher',
        ),
    ]
